name: Testing Checks

on:
  pull_request:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build CI Docker Image"]
    types:
      - completed

jobs:
  test:
    name: Testing Checks
    runs-on: ubuntu-latest
    # Skip if triggered by workflow_run and the CI image build failed
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    container:
      image: ghcr.io/cs24-1/cs24-1-bot-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      checks: write
      contents: read
      pull-requests: write
      packages: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests with coverage
        run: |
          pytest --cov-report=xml:coverage.xml --cov

      - name: Comment coverage report
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ./coverage.xml
          junitxml-path: ./pytest.xml
